# Generated by Django 4.2.7 on 2025-10-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL标识')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客标签',
                'verbose_name_plural': '博客标签',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL标识')),
                ('content_markdown', models.TextField(verbose_name='Markdown内容')),
                ('content_html', models.TextField(blank=True, verbose_name='HTML内容')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='特色图片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogs.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='blogs.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'ordering': ['-created_at'],
            },
        ),
    ]
