version: "3.9"

services:
  web:
    build: .
    container_name: blog_backend
    env_file:
      - ./env.example
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blog_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      GUNICORN_WORKERS: 3
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/app/entrypoint.sh"]

  db:
    image: postgres:15
    container_name: blog_db
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
