version: "3.9"

services:
  web:
    build: .
    container_name: blog_backend
    env_file:
      - ./.env
    environment:
      # 开发环境使用本地数据库
      DB_ENGINE: django.db.backends.mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: blog_db
      DB_USER: root
      DB_PASSWORD: root
      GUNICORN_WORKERS: 3
      GUNICORN_BIND: 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["/app/entrypoint.sh"]
    # 生产环境注释掉db依赖，使用外部数据库
    # depends_on:
    #   - db

  # 开发环境数据库，生产环境使用阿里云RDS MySQL
  db:
    image: mysql:8.0
    container_name: blog_db
    environment:
      MYSQL_DATABASE: blog_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysqldata:
